---
pipeline:
  lint:
    group: ci
    image: golangci/golangci-lint:v1.38.0
    commands:
      - make lint

  test:
    group: ci
    image: golang:1.16-alpine
    commands:
      - apk add --update make
      - make test
