name: publish image
on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Checkout code
      uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: --config .golangci.yml
        version: v1.41.0
    - name: Test
      run: go test ./...
  build:
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and publish image to Quay
      uses: docker/build-push-action@v1
      with:
         context: .
         push: true
         registry: quay.io
         repository: packet/ironlib
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         tags: latest
